### PR TITLE
Setup for Testnet Release

### LINKED ISSUE #18: Handle incorrect password
If the user types in an incorrect password when signing in or when approving a transaction, they should get feedback through signer UI

### LINKED ISSUE #19: Handle close window
If a user closes the manta-signer window (either the main window or the about window), it is gone forever and can't be reopened

### LINKED ISSUE #20: Can't quit sometimes
Sometimes, for unknown reasons, it is not possible to quit Signer through the "Quit" item on the menu bar

### PR DESCRIPTION
**Pull request by bhgomes**
- [x] add password retry (Closes #18) @bhgomes 
- [x] handle closing windows (closes #19 closes #20) @Kevingislason 
- [x] add testing workflow @bhgomes 
- [ ] add release strategy @bhgomes

### CODE REVIEW

**Comment by bhgomes** [comment]
@Kevingislason Could you take a look at the JS code whenever you have the chance? I believe I have the new state machine working, but there seem to be issues with the UI in general. I'll try and solve them tomorrow as well.

**Comment by Kevingislason** [comment]
re: closing windows: I retained decorations. If the user tries to close the window on the main page, nothing happens. If the user tries to close the window on the about page, the about window gets hidden. 

I tried handling close window requests more intelligently, so that closing the window during authorize declines the transaction. It's less clear how to handle window close during "sign in" and "create account". Suffice it to say, this approach is far more trouble than it's worth. I got declining transactions on close window to work, but sign in was a problem--if you close the Sign in window, when does it reopen? There are some major problems communicating between the service, the rust tauri code, and the front end.

After giving up on the above, I tried getting rid of decorations, but I couldn't figure out how to round the corners of signer's window, which makes it unacceptably ugly.

**Comment by bhgomes** [comment]
> I tried handling close window requests more intelligently, so that closing the window during authorize declines the transaction. It's less clear how to handle window close during "sign in" and "create account". Suffice it to say, this approach is far more trouble than it's worth. I got declining transactions on close window to work, but sign in was a problem--if you close the Sign in window, when does it reopen? There are some major problems communicating between the service, the rust tauri code, and the front end.

Yeah, I think probably the correct answer is that if they close the window on create account or login it should quit the app entirely.

> After giving up on the above, I tried getting rid of decorations, but I couldn't figure out how to round the corners of signer's window, which makes it unacceptably ugly.

You can make the window transparent (in the Tauri config) and then do a nonzero border-radius in the CSS. Let's keep decorations for now though.

File: src/service.rs [hunk 1]
```diff
@@ -273,14 +305,22 @@ where
...
+    A::Error: Send,
 {
     /// Builds a new [`Service`] from `config` and `authorizer`.
     #[inline]
     pub fn build(config: Config, authorizer: A) -> Self {
+        // FIXME: This is not the best strategy for choosing which URL we want.
+        #[cfg(debug_assertions)]
+        let url = config.dev_origin_url.as_str();
+        #[cfg(not(debug_assertions))]
+        let url = config.prod_origin_url.as_str();
```
Comment (Kevingislason) [inline src/service.rs:319]: Do you have anything against us allowing both CORS urls always? It is a bit inconvenient to have to manage separate prod and dev builds.

**Review by Kevingislason — APPROVED** [review]
Ran the tests on deployed version of testnet UI, everything working

LGTM

File: src/service.rs (hunk 1 above)
Comment (bhgomes) [reply src/service.rs:319]: I don't want the `localhost` allowed on the production build. That's a super easy way to spoof the frontend with a trojan and we should also not test some production parts with non-production parts. I just wish there was a better way to structure this instead of relying on `debug_assertions` which is a bit sketchy but technically safe.
